let a = 5;
let b = 10;
console.log(a + b);
try{
    console.log(a+ c);
} catch(err){
    console.log(err)
}